//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgancyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationGo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DestinationGo()
        {
            this.TimeGoes = new HashSet<TimeGo>();
            this.Travelers = new HashSet<Traveler>();
        }
    
        public int DestinationGoID { get; set; }
        public string DestinationName { get; set; }
        public Nullable<int> TravelID { get; set; }
    
        public virtual Travel Travel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeGo> TimeGoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traveler> Travelers { get; set; }
    }
}
