//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgancyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationBack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DestinationBack()
        {
            this.TimeBacks = new HashSet<TimeBack>();
            this.Travelers = new HashSet<Traveler>();
        }
    
        public int DestinationBackID { get; set; }
        public Nullable<int> TravelID { get; set; }
        public string DestinationNameB { get; set; }
    
        public virtual Travel Travel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeBack> TimeBacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traveler> Travelers { get; set; }
    }
}
