//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgancyPro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelAgancyEntities : DbContext
    {
        public TravelAgancyEntities()
            : base("name=TravelAgancyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DestinationBack> DestinationBacks { get; set; }
        public virtual DbSet<DestinationGo> DestinationGoes { get; set; }
        public virtual DbSet<TimeBack> TimeBacks { get; set; }
        public virtual DbSet<TimeGo> TimeGoes { get; set; }
        public virtual DbSet<Travel> Travels { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Traveler> Travelers { get; set; }
        public virtual DbSet<TimeLine> TimeLines { get; set; }
    }
}
