//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgancyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traveler
    {
        public string UserID { get; set; }
        public Nullable<int> TravelID { get; set; }
        public Nullable<int> DestinationGoID { get; set; }
        public Nullable<int> DestinationBackID { get; set; }
        public Nullable<int> TimeGoID { get; set; }
        public Nullable<int> TimeBackID { get; set; }
        public int id { get; set; }
        public string ReferenceNo { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual DestinationBack DestinationBack { get; set; }
        public virtual DestinationGo DestinationGo { get; set; }
        public virtual TimeBack TimeBack { get; set; }
        public virtual TimeGo TimeGo { get; set; }
        public virtual Travel Travel { get; set; }
    }
}
